### DISCUSSION TITLE
Any steps to enabled web dashboard.

### DISCUSSION THREAD

**Discussion by cclim123** [arkmq-org/arkmq-org-broker-operator#1024] [Q&A] [answered]
Hi,
  I plan to deploy in our on-prem openshift. So far yet come across article steps to enabled dashboard to view queue and topic status. 
  I would be happy if someone can share.

**Comment by brusdev** [comment, marked as answer]
@cclim123 you can use the `.spec.console.expose` field to expose the ActiveMQ Artemis Web Console, i.e. use the following ActiveMQArtemis CR to deploy a broker instance and expose its console at http://artemis-with-console.my-domain.com

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-with-console
spec:
  console:
    expose: true
    ingressHost: artemis-with-console.my-domain.com
```
