### DISCUSSION TITLE
How to unset expiry-address

### DISCUSSION THREAD

**Discussion by sburkard** [arkmq-org/arkmq-org-broker-operator#1057] [Q&A] [answered]
I want to get rid of the expiry-address named `ExpiryQueue` that is by default configured for all queues on the operator based broker. I want expired messages to be automatically deleted.  

According to [this discussion](https://github.com/artemiscloud/activemq-artemis-operator/discussions/853) I have configured my Broker's address settings to 

```
addressSettings:
  addressSetting:
    - match: '#'
      expiryAddress: ""
```

When I check the `/home/jboss/amq-broker/etc/broker.xml` config directly in the broker pod, it is correctly reflected there

```
<address-setting match="#">
  <expiry-address></expiry-address>
```
Unfortunately it does not work. When I check the attributes of the queues in the Broker console, existing queues still have the `ExpiryQueue` assigned and even newly created queues have the `ExpiryQueue` as expiry address. 

![image](https://github.com/user-attachments/assets/8fb70d2e-d8bc-4056-8ade-f8950bc6bbb0)

Broker version is: 2.28.0.redhat-00022

Any suggestions? 
Thanks and regards

**Comment by brusdev** [comment]
Broker version 2.28.0.redhat-00022 is supported by Red Hat.

Are you able to reproduce this issue with the latest ArtemisCloud Operator release: https://github.com/artemiscloud/activemq-artemis-operator/releases/tag/1.2.7 ?

Can you share your ActiveMQArtemis CR?

**Comment by sburkard** [comment]
Hi @brusdev 

Ah, now I realize that this Github repo is not the home of the RedHat operator. Is RedHat using your operator as base or vice versa? 

Here is my CR. 

What I think really works is the `managementMessageAttributeSizeLimit: -1`. Because before we just saw the first part of the messages and now we see the entire message in the Browser console. 

However, the dead-letter and expiry-address settings do not work. The queues still have a central `DLQ` and `ExpiryQueue` as by default.

ActiveMQArtemis CR

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: misc-broker
spec:
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    requireLogin: false
    storage:
      size: 25Gi
    resources:
      limits:
        cpu: 2
        memory: 4096Mi
      requests:
        cpu: 1
        memory: 2048Mi
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: true
    image: placeholder
  adminUser: admin
  console:
    expose: true
    sslEnabled: true
    sslSecret: misc-broker-amqp-secret
  acceptors:
    - name: openwire
      protocols: openwire
      port: 61452
      sslEnabled: true
      sslSecret: misc-broker-amqp-secret
      verifyHost: false
      expose: true
      needClientAuth: true
  addressSettings:
    addressSetting:
      - match: '#'
        managementMessageAttributeSizeLimit: -1
        autoCreateDeadLetterResources: true
        deadLetterQueuePrefix: DLQ.
        deadLetterQueueSuffix: ""
        expiryAddress: ""
```

The configuration above leads to this broker.xml (/home/jboss/amq-broker/etc/broker.xml)
```
<?xml version='1.0'?>
<configuration xmlns="urn:activemq" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
	<core xmlns="urn:activemq:core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq:core ">
		<name>amq-broker</name>
		<persistence-enabled>true</persistence-enabled>
		<max-redelivery-records>1</max-redelivery-records>
		<journal-type>NIO</journal-type>
		<paging-directory>/opt/misc-broker/data/paging</paging-directory>
		<bindings-directory>/opt/misc-broker/data/bindings</bindings-directory>
		<journal-directory>/opt/misc-broker/data/journal</journal-directory>
		<large-messages-directory>/opt/misc-broker/data/large-messages</large-messages-directory>
		<journal-datasync>true</journal-datasync>
		<journal-min-files>2</journal-min-files>
		<journal-pool-files>10</journal-pool-files>
		<journal-device-block-size>4096</journal-device-block-size>
		<journal-file-size>10M</journal-file-size>
		<connectors>
			<connector name="artemis">tcp://*****.svc.cluster.local:61616</connector>
		</connectors>
		<disk-scan-period>5000</disk-scan-period>
		<max-disk-usage>90</max-disk-usage>
		<critical-analyzer>true</critical-analyzer>
		<critical-analyzer-timeout>120000</critical-analyzer-timeout>
		<critical-analyzer-check-period>60000</critical-analyzer-check-period>
		<critical-analyzer-policy>HALT</critical-analyzer-policy>
		<global-max-messages>-1</global-max-messages>
		<acceptors>
			<acceptor name="openwire">tcp://*****.svc.cluster.local:61452?protocols=OPENWIRE;sslEnabled=true;keyStorePath=/etc/misc-broker-amqp-secret-volume/broker.ks;keyStorePassword=*****;trustStorePath=/etc/misc-broker-amqp-secret-volume/client.ts;trustStorePassword=*****;;needClientAuth=true;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor>
			<acceptor name="scaleDown">tcp://*****.svc.cluster.local:61616?protocols=CORE;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor>
		</acceptors>
		<cluster-user>*****</cluster-user>
		<cluster-password>*****</cluster-password>
		<broadcast-groups>
			<broadcast-group name="my-broadcast-group">
				<jgroups-file>jgroups-ping.xml</jgroups-file>
				<jgroups-channel>activemq_broadcast_channel</jgroups-channel>
				<connector-ref>artemis</connector-ref>
			</broadcast-group>
		</broadcast-groups>
		<discovery-groups>
			<discovery-group name="my-discovery-group">
				<jgroups-file>jgroups-ping.xml</jgroups-file>
				<jgroups-channel>activemq_broadcast_channel</jgroups-channel>
				<refresh-timeout>10000</refresh-timeout>
			</discovery-group>
		</discovery-groups>
		<cluster-connections>
			<cluster-connection name="my-cluster">
				<connector-ref>artemis</connector-ref>
				<retry-interval>1000</retry-interval>
				<retry-interval-multiplier>2</retry-interval-multiplier>
				<max-retry-interval>32000</max-retry-interval>
				<initial-connect-attempts>20</initial-connect-attempts>
				<reconnect-attempts>10</reconnect-attempts>
				<use-duplicate-detection>true</use-duplicate-detection>
				<message-load-balancing>ON_DEMAND</message-load-balancing>
				<max-hops>1</max-hops>
				<discovery-group-ref discovery-group-name="my-discovery-group"/>
			</cluster-connection>
		</cluster-connections>
		<security-settings>
			<security-setting match="#">
				<permission type="createNonDurableQueue" roles="admin"/>
				<permission type="deleteNonDurableQueue" roles="admin"/>
				<permission type="createDurableQueue" roles="admin"/>
				<permission type="deleteDurableQueue" roles="admin"/>
				<permission type="createAddress" roles="admin"/>
				<permission type="deleteAddress" roles="admin"/>
				<permission type="consume" roles="admin"/>
				<permission type="browse" roles="admin"/>
				<permission type="send" roles="admin"/>
				<permission type="manage" roles="admin"/>
			</security-setting>
		</security-settings>
		<address-settings>
			<!-- if you define auto-create on certain queues, management has to be auto-create -->
			<address-setting match="activemq.management#">
				<dead-letter-address>DLQ</dead-letter-address>
				<expiry-address>ExpiryQueue</expiry-address>
				<redelivery-delay>0</redelivery-delay>
				<max-size-bytes>-1</max-size-bytes>
				<message-counter-history-day-limit>10</message-counter-history-day-limit>
				<address-full-policy>PAGE</address-full-policy>
				<auto-create-queues>true</auto-create-queues>
				<auto-create-addresses>true</auto-create-addresses>
			</address-setting>
			<address-setting match="#">
				<expiry-address/>
				<auto-create-dead-letter-resources>true</auto-create-dead-letter-resources>
				<dead-letter-queue-suffix/>
				<dead-letter-queue-prefix>DLQ.</dead-letter-queue-prefix>
				<management-message-attribute-size-limit>-1</management-message-attribute-size-limit>
				<redistribution-delay>0</redistribution-delay>
				<dead-letter-address>DLQ</dead-letter-address>
				<redelivery-delay>0</redelivery-delay>
				<max-size-bytes>-1</max-size-bytes>
				<max-size-messages>-1</max-size-messages>
				<page-size-bytes>10M</page-size-bytes>
				<max-read-page-messages>-1</max-read-page-messages>
				<max-read-page-bytes>20M</max-read-page-bytes>
				<message-counter-history-day-limit>10</message-counter-history-day-limit>
				<address-full-policy>PAGE</address-full-policy>
				<auto-create-queues>true</auto-create-queues>
				<auto-create-addresses>true</auto-create-addresses>
				<auto-delete-queues>false</auto-delete-queues>
				<auto-delete-addresses>false</auto-delete-addresses>
			</address-setting>
		</address-settings>
		<addresses>
			<address name="DLQ">
				<anycast>
					<queue name="DLQ"/>
				</anycast>
			</address>
			<address name="ExpiryQueue">
				<anycast>
					<queue name="ExpiryQueue"/>
				</anycast>
			</address>
		</addresses>
	</core>
</configuration>
```
