### DISCUSSION TITLE
auto-delete-queues-skip-usage-check and auto-delete-addresses-skip-usage-check support in address setting

### DISCUSSION THREAD

**Discussion by lnthai2002** [arkmq-org/arkmq-org-broker-operator#1102] [Q&A]
Hi, in artemis broker 2.33.0 there are **auto-delete-addresses-skip-usage-check** and **auto-delete-queues-skip-usage-check** for address settings: https://activemq.apache.org/components/artemis/documentation/2.33.0/address-settings.html#address-settings. However it does not seem that these settings are accepted by operator. Is there a work around to set those settings?

**Comment by brusdev** [comment]
Hi @lnthai2002 you can use the broker properties to set auto-delete-addresses-skip-usage-check and auto-delete-queues-skip-usage-check for address settings, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-address-settings
spec:
  brokerProperties:
    - 'addressesSettings.#.autoDeleteAddressesSkipUsageCheck=true'
    - 'addressesSettings.#.autoDeleteQueuesSkipUsageCheck=true'
```
