### DISCUSSION TITLE
Redeploy chart does not update addressSettings

### DISCUSSION THREAD

**Discussion by lnthai2002** [arkmq-org/arkmq-org-broker-operator#1104] [Q&A]
Hi,
I am using artemis operator 1.2.1 which deploy artemis broker 2.33. I have a helm chart containing the definition of ActiveMQArtemis kind with all the follwing address settings:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: activemq-artemis-broker
spec:
  acceptors:
    - name: "all-protocols-acceptor"
      bindToAllInterfaces: true
      port: 61617
#      protocols: "CORE" # not defining protocols make broker enable all protocols (CORE,STOMP, AMQP,...) support
  addressSettings:
    applyRule: merge_all
    addressSetting:
    - match: '#'
      deadLetterAddress: DLQ
      expiryAddress: ExpiryQueue
      redistributionDelay: 60000
      redeliveryDelay: 0
      maxSizeBytes: "-1"
      messageCounterHistoryDayLimit: 10
      addressFullPolicy: PAGE
      autoCreateQueues: true
      autoCreateAddresses: true
      autoCreateJmsQueues: true
      autoCreateJmsTopics: true
      autoDeleteQueues: true
      autoDeleteQueuesDelay: 300000
      autoDeleteCreatedQueues: true
      autoDeleteAddresses: true
      defaultConsumerWindowSize: 0
    - match: 'JOB_QUEUE.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
    - match: 'CRON_JOB_QUEUE.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
...
```
After I deployed my chart, I used management API (https://activemq.apache.org/components/artemis/documentation/javadocs/javadoc-latest/org/apache/activemq/artemis/api/core/management/ActiveMQServerControl.html#getAddressSettingsAsJSON(java.lang.String)) to get the addressSetting from the running broker and it matched the settings I provided in the chart. Then I added a new match section to the chart:
```
...
    - match: 'CRON_MESSAGE_QUEUE.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
...
```
and redeployed the chart (undeploy old one and deploy new), however when I got the address settings using management api I didnt see the new addressSetting I just added. Could you please advise ?
