### DISCUSSION TITLE
Question About SSL Connection

### DISCUSSION THREAD

**Discussion by subhidh-agarwal** [arkmq-org/arkmq-org-broker-operator#1120] [Q&A] [answered]
I have a similar requirement - https://arkmq.org/docs/tutorials/send_receive_ingress/
The problem im facing - I dont have a trust cert becasue the cert (broker.ks) is issued by Lets Encrypt. So not sure how do I do this.

and also , How can I make my custom host for ingress? As of now i see it follows a pattern.

Below mentioned is the broker 
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
  ingressDomain: amq-operator.company.net
  acceptors:
  - name: sslacceptor
    protocols: all
    port: 62626
    expose: true
    sslEnabled: true
    sslSecret: tls-activemq-operator
```

The host created is - ```artemis-broker-sslacceptor-0-svc-ing-amq-mvp.amq-operator.company.net```
I needed something else like - ```broker1.amq-operator.company.net```
