### DISCUSSION TITLE
ActiveMQArtemis with different address full policy per queue

### DISCUSSION THREAD

**Discussion by dj-wasabi** [arkmq-org/arkmq-org-broker-operator#1153] [Q&A] [answered]
Hi,

I am trying to migrate to this operator and in the old setup, I have the following configured:

```
    <address-settings>
      <address-setting match="#">
        <address-full-policy>PAGE</address-full-policy>
      <address-setting match="something.interesting">
        <address-full-policy>FAIL</address-full-policy>
      </address-setting>
      <address-setting match="something.interesting.aswell">
        <address-full-policy>FAIL</address-full-policy>
      </address-setting>
    </address-settings>
```
How am I to translate this to a `ActiveMQArtemis` setup? I don't know exactly how to configure the `brokerProperties` property for this, especially for the FAIL policy.

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 2
    messageMigration: true
    persistenceEnabled: true
  brokerProperties:
    - "address-full-policy=PAGE"
 ```
I see this https://github.com/arkmq-org/activemq-artemis-operator/discussions/1025#discussioncomment-11474154 comment, but I think the broker-0 and broker-1 are specific to the actual pods and not as in list order.

Thanks in advance.
