### DISCUSSION TITLE
Certificate Revocation List

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#416] [Q&A] [answered]
Is it possible to configure a Certificate Revocation List via Artemis CRD? 
I saw a possible solution from [here](https://github.com/apache/activemq-artemis/tree/main/examples/features/standard/ssl-enabled-crl-mqtt) but I don't know how to add **crlPath=other-client-crl.pem** via Artemis CRD. 
Is it feasible?
TIA.

**Comment by brusdev** [comment, marked as answer]
The `brokerProperties` can be used to set acceptor params not defined in ActiveMQArtemis CRD, and the `other-client-crl.pem` file can be included in a secret and mounted using `extraMounts`, i.e.

kubectl create secret generic my-crl-secret --from-file=other-client-crl.pem=./other-client-crl.pem

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-mqtt-ssl-crl
spec:
  deploymentPlan:
    size: 1
    image: placeholder
    extraMounts:
      secrets:
        - my-crl-secret
  acceptors:
  - name: my-mqtt-acceptor
    protocols: MQTT
    port: 8883
    sslEnabled: true
  brokerProperties:
    - "acceptorConfigurations.my-mqtt-acceptor.params.crlPath=/amq/extra/secretes/my-crl-secret/other-client-crl.pem"
```
