### DISCUSSION TITLE
High Availability

### DISCUSSION THREAD

**Discussion by clopezhe360** [arkmq-org/arkmq-org-broker-operator#419] [Q&A] [answered]
I've successfully deployed the operator to my Kubernetes cluster along with the brokers. I noticed that in the Broker chart there's this line:
```
  deploymentPlan:
    size: 1
```

From my testing, if i change that to 2, it'll deploy two brokers. Does that mean High Availability gets configured automatically by the broker and my messages/queues will not get lost when one of my brokers goes down?

**Comment by brusdev** [comment, marked as answer]
The High Availability is provided with `messageMigration` and the persistence is provided persisting messages to persistent storage with `persistenceEnabled`, i.e.

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-ha
spec:
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    messageMigration: true
```
