### DISCUSSION TITLE
Drainer job vs. Istio sidecar

### DISCUSSION THREAD

**Discussion by agentp-1337** [arkmq-org/arkmq-org-broker-operator#432] [Q&A] [answered]
Dear Artemis Operator team

I've setup the ActiveMQ Artemis cluster within a k8s cluster incl. istio as a service mesh. So far everything worked fine. The only problem I'm facing now is during the drainer job is executed. After the messages have been migrated the drainer job completes but the istio sidecar is not stopped and therefor the whole jobs remain in state NotReady.

Is it possible to add a custom command to the drainer.sh? Something like "curl -X POST http://localhost:15020/quitquitquit" to stop the istio sidecar? If I'm doing it manually everything works fine.

Many thx for your support.

Best regards
Mirco

**Comment by brusdev** [comment, marked as answer]
There is no way to add a custom command to the drainer.sh in the ActiveMQArtemis CRD, you could build your own custom broker container image:

1.  Create a custom drain.sh, i.e
```
#!/bin/sh

/opt/amq/bin/internal-drain.sh

curl -X POST http://localhost:15020/quitquitquit
```

2. Create a Dockerfile, i.e.
```
FROM quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.27.0
RUN mv /opt/amq/bin/drain.sh /opt/amq/bin/internal-drain.sh
COPY drain.sh /opt/amq/bin/drain.sh
CMD /opt/amq/bin/launch.sh start
```

3. Build the custom broker container image, i.e
```
docker build --tag quay.io/<YOUR-QUAY-ORG>/activemq-artemis-broker-kubernetes:artemis.2.27.0 .
```

4. Push the custom broker container image, i.e.
```
docker push quay.io/<YOUR-QUAY-ORG>/activemq-artemis-broker-kubernetes:artemis.2.27.0
```

5. Use the custom broker container image, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
    image: quay.io/<YOUR-QUAY-ORG>/activemq-artemis-broker-kubernetes:artemis.2.27.0
```
