### DISCUSSION TITLE
Add users and roles

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#463] [Q&A] [answered]
I would like to add new users and roles to an Artemis Cluster installed via Operator. To add new entries to artemis-users.properties and artemis-roles.properties as best practice do I need to to use init image to change these files?
Is it possible to add users and roles dynamically?

**Comment by brusdev** [comment, marked as answer]
Staring from the next release the operator will support Configurable JAAS authentication, for further details see https://github.com/artemiscloud/activemq-artemis-operator/issues/356

The current solution is to use the ActiveMQSecurity, i.e.:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: security-login
spec:
  loginModules:
    propertiesLoginModules:
      - name: "prop-module"
        users:
          - name: user123456
            password: "a123456"
            roles:
              - "admin"
  securityDomains:
    brokerDomain:
      name: "activemq"
      loginModules:
        - name: "prop-module"
          flag: "sufficient"
```
