### DISCUSSION TITLE
Is it possible to deploy queues from a list of values?

### DISCUSSION THREAD

**Discussion by Nish07** [arkmq-org/arkmq-org-broker-operator#545] [Q&A] [answered]
When deploying the my queue chart it only creates the Test3 address name and Test3-Queue. 

Just wondering if it's possible with the current operator?

Here's my chart:

```
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: {{ .Values.service.name }}
spec:
 {{- range $address := .Values.addresses }}
 {{- with $ }}
  addressName: {{ $address.addressName }}
  queueName: {{ $address.queueName }}
  routingType: {{ $address.routingType }}
  removeFromBrokerOnDelete: true
{{ end }}
{{- end }}

```

Values:

```
addresses:
- addressName: Test1
  queueName: Test1-QUEUE
  routingType: anycast
- addressName: Test2
  queueName: Test2-QUEUE
  routingType: anycast
- addressName: Test3
  queueName: Test3-QUEUE
  routingType: anycast

```

**Comment by brusdev** [comment, marked as answer]
You could use broker properties to define multiple addresses in on CR, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-addresses
spec:
  brokerProperties:
    - "addressConfigurations.Test1.routingTypes=ANYCAST"
    - "addressConfigurations.Test1.queueConfigs.Test1-QUEUE.address=Test1"
    - "addressConfigurations.Test1.queueConfigs.Test1-QUEUE.routingType=ANYCAST"
    - "addressConfigurations.Test2.routingTypes=ANYCAST"
    - "addressConfigurations.Test2.queueConfigs.Test2-QUEUE.address=Test2"
    - "addressConfigurations.Test2.queueConfigs.Test2-QUEUE.routingType=ANYCAST"
    - "addressConfigurations.Test3.routingTypes=ANYCAST"
    - "addressConfigurations.Test3.queueConfigs.Test3-QUEUE.address=Test3"
    - "addressConfigurations.Test3.queueConfigs.Test3-QUEUE.routingType=ANYCAST"
...
```
