### DISCUSSION TITLE
Node Manager can not open file /opt/activemq-artemis-broker/data/journal/server.lock java.io.IOException: No such file or directory

### DISCUSSION THREAD

**Discussion by lnthai2002** [arkmq-org/arkmq-org-broker-operator#547] [Q&A] [answered]
Hi i am trying to enable persistence for my broker, here is the deployment plan section:
```
deploymentPlan:
    size: {{ .Values.replicas }}
    image: placeholder
    requireLogin: true
    persistenceEnabled: {{ .Values.persistence.enabled }}
    {{- if .Values.persistence.enabled }}
    storage:
      size: {{ .Values.persistence.size }}
      storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    resources:
      requests:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
```

I am running k3s and i created a persistence volume as follow:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: gp2-ncp
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/my-pv
```
however, when i deploy the plan, i got this error:
`MQ222141: Node Manager can not open file /opt/activemq-artemis-broker/data/journal/server.lock
java.io.IOException: No such file or directory`
I'm not sure if this is due to my PV not set up correctly or i am missing a config in my deploymentPlan. Hope to get some hint on this.
Thai Le
