### DISCUSSION TITLE
Zero Persistence

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#549] [Q&A]
I've tryed to disable broker persistence (e.g zero persistence) with the following Artemis CRD definition:

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: exoo
spec:
  deploymentPlan:
    size: 1
    image: placeholder
    extraMounts:
      secrets:
        - cert-jaas-config
    labels:
      app: artemis-cluster
  acceptors:
    - name: tcp-mqtt-acceptor
      protocols: MQTT
      port: 61616
      expose: false
      sslEnabled: false
  console:
    expose: true
  brokerProperties:
    - 'persistenceEnabled=false'
```

but looking at JMX console the PersistenceEnabled flag is set to true.
Is it the right way to set this parameter or I need to create a custom init image to set persistence-enabled in broker.xml to false?
