### DISCUSSION TITLE
How to set address-queue-scan-period

### DISCUSSION THREAD

**Discussion by lnthai2002** [arkmq-org/arkmq-org-broker-operator#561] [General] [answered]
Hello, the Artemis doc said that "address-queue-scan-period" can be used to control how often broker scan queues for potential delete. However, i don't see anything in the broker.amq.io_activemqartemises.yaml that resemble this setting. If it is not configurable in ActiveMQArtemis crd how can I set different values to this setting (default is 30 sec)

**Comment by brusdev** [comment, marked as answer]
You can set `address-queue-scan-period` setting using the broker properties, i.e.

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-id-cache
spec:
  brokerProperties:
    - "addressQueueScanPeriod=5000"
```
