### DISCUSSION TITLE
How to configure a remote broker

### DISCUSSION THREAD

**Discussion by jseiser** [arkmq-org/arkmq-org-broker-operator#576] [General] [answered]
https://activemq.apache.org/components/artemis/documentation/latest/amqp-broker-connections.html

We currently use ActiveMQ Classic, and have a network broker defined, with a remote ActiveMQ Classic that we have configured as `duplex` where we push/pull messages.

Using the CRDs, is there a way to mirror that? To be clear, we do not use any queues, just topics. I think it would be something
like the below if we were just doing it by hand.

```
<broker-connection>
  <amqp-connection uri="tcp://brokerB:5672" name="brokerB"> <-- remote ActiveMQ Classic IP?
    <mirror/>
  </amqp-connection>
</broker-connection>
```

**Comment by brusdev** [comment, marked as answer]
You can define a broker-connection using brokerProperties, i.e.:

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-test
spec:
  brokerProperties:
    - "AMQPConnections.brokerB.uri=tcp://brokerB:5672"
```

To get help on the ActiveMQ Artemis project you can send an email to users@activemq.apache.org
