### DISCUSSION TITLE
How to Expose Services externally

### DISCUSSION THREAD

**Discussion by jseiser** [arkmq-org/arkmq-org-broker-operator#586] [General] [answered]
Im not seeing anything in the documentation, that discuses how to configure the services being created for the various accepters.  e.g., I would want openwire to be expose externally via  service of type load balancer, with annotations in place to properly configure the AWS NLB.

Thanks,

**Comment by gaohoward** [comment]
if you set expose to true for the acceptor, the operator will create a service of type ClusterIP and an ingress. 
You may try it and see if that meets your requirement.

**Reply by jseiser** [reply]
Can you point me to more documentation on the ingress?

I would not expect an ingress to work, since it would only expose ports 80/443, and in our instance, has alot of additional requirements. 

e.g.

```
❯ kubectl get ingress -n monitoring kube-prometheus-stack-alertmanager -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-r53-prod <-- Cluster Issuer for the TLS on the Ingress
    nginx.ingress.kubernetes.io/service-upstream: "true" <-- mesh


  tls:
  - hosts:
    - real.domain.com
    secretName: am-prod-tls <-- name of the secret to host the TLS cert
```


A setup like the above, would not allow for a consumer to have the proper TLS information to connect with TLS Authentication.  It also would require them to send traffic to 443, not 61617 for instance.

The only way i have seen this work in k8s, is by exposing these as serviceType: Load Balancer.

**Reply by brusdev** [reply]
The Ingress resources created by the operator for the acceptors with expose=true require sslEnabled:true and an Ingress controller with ssl-passthrough enabled. The Ingress controller will forward the IP packets received on the port 443 to the broker acceptor port.

**Reply by jseiser** [reply]
@brusdev 

Wouldnt ssl pass through, require being able to set annotation on the created ingress like I was asking in the previous post?


```
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-r53-prod <-- Cluster Issuer for the TLS on the Ingress
    nginx.ingress.kubernetes.io/service-upstream: "true" <-- mesh
    nginx.ingress.kubernetes.io/ssl-passthrough: "true" <-- enable pass through
```
