### DISCUSSION TITLE
Headless Service without exposed acceptor

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#609] [Q&A] [answered]
Hi all,
I used this CRD to create an Artemis Cluster with two nodes

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: exoo
spec:
  deploymentPlan:
    size: 2
    labels:
      app: artemis-cluster
  acceptors:
    - name: tcp-mqtt
      protocols: MQTT
      port: 61616
      expose: false
      sslEnabled: false
    - name: tcp-mqtt-tls
      protocols: MQTT
      port: 61617
      expose: false
      sslEnabled: true
      needClientAuth: true
      verifyHost: false
```

and I saw that an headless service has been created with only these ports

```yaml
ports:
  - name: console-jolokia
    port: 8161
    protocol: TCP
    targetPort: 8161
  - name: all
    port: 61616
    protocol: TCP
    targetPort: 61616
```

Do I need to create a new one for the acceptor tcp-mqtt-tls? I need it because I have to configure an Istio Gatewy and an Istio Virtual Service to expose it outside the cluster something like

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mqtt-ssl-gateway
spec:
  hosts:
  - "artemisbroker.sap.dev"
  gateways:
  - artemis-gateway
  tls:
  - match:
    - port: 61617
      sniHosts:
      - "artemisbroker.sap.dev"
    route:
    - destination:
        host: exoo-tcp-mqtt-tls-0-svc
        port: 
          number: 61617
```

But as you can see inside the destination field you can specify a single host so with two nodes this doesn't work becasue there is one service per Artemis node namely

- exoo-tcp-mqtt-tls-0-svc
- exoo-tcp-mqtt-tls-1-svc

Any advice?
