### DISCUSSION TITLE
Define MQTT+TLS and WebSocket+TLS support

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#610] [Q&A] [answered]
Is it possible to define two acceptor namely:

1. MQTT+TLS
2. WebSocket+TLS

at the same time?
Do I need to define two secret one for each acceptor following the naming convention `<cr-name>-<acceptor-name>-secret`?

**Comment by brusdev** [comment, marked as answer]
Use the `SSLSecret` field to reuse a same secret for multiple acceptors, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: exoo
spec:
  deploymentPlan:
  acceptors:
    - name: mqtt-tls
      sslSecret: my-secret
      ...
    - name: ws-tls
      sslSecret: my-secret
      ...
```

**Comment by lordigon** [comment]
@brusdev just another question that comes to my mind: is it possible to use different certificates for the two acceptor?

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: exoo
spec:
  deploymentPlan:
  acceptors:
    - name: mqtt-tls
      sslSecret: my-secret-1
      ...
    - name: ws-tls
      sslSecret: my-secret-2
      ...
```
