### DISCUSSION TITLE
How to configure 'allowLinkStealing' on acceptors

### DISCUSSION THREAD

**Discussion by eanbiso** [arkmq-org/arkmq-org-broker-operator#635] [Q&A] [answered]
Hi support,
I would need to understand how I can configure the property 'allowLinkStealing' on an MQTT acceptor using Artemis in the k8s context.
With [ARTEMIS-4200](https://issues.apache.org/jira/browse/ARTEMIS-4200) the possibility to disable stealing link on MQTT protocol has been introduced in Artemis 2.29.0 and is configurable on the acceptor through the parameter "allowLinkStealing", like shown here: 
```
 <acceptor name="mqtt-plain">tcp://0.0.0.0:1884?
 tcpSendBufferSize=1048576;
 tcpReceiveBufferSize=1048576;
 protocols=MQTT;
 useEpoll=true;
 allowLinkStealing=false;
</acceptor>
```
How can I apply same configuration using the Operator?
I was looking for the acceptors configuration in the [broker_activemqartemis_crd.yaml (v1.0.13)](https://github.com/artemiscloud/activemq-artemis-operator/blob/v1.0.13/deploy/crds/broker_activemqartemis_crd.yaml), but I didn't find a setting like this.

Can you help me?

**Comment by brusdev** [comment, marked as answer]
Hi @eanbiso, you can use broker properties to customize or define an acceptor, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-mqtt
spec:
  acceptors:
    - name: mqtt-plain
      protocols: MQTT
      port: 1884
  brokerProperties:
    - "acceptorConfigurations.mqtt-plain.extraParams.allowLinkStealing=false"
```

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-mqtt-bp
spec:
  brokerProperties:
    - "acceptorConfigurations.mqtt-plain.params.host=0.0.0.0"
    - "acceptorConfigurations.mqtt-plain.params.port=1884"
    - "acceptorConfigurations.mqtt-plain.params.tcpSendBufferSize=1048576"
    - "acceptorConfigurations.mqtt-plain.params.tcpReceiveBufferSize=1048576"
    - "acceptorConfigurations.mqtt-plain.params.protocols=MQTT"
    - "acceptorConfigurations.mqtt-plain.params.useEpoll=true"
    - "acceptorConfigurations.mqtt-plain.extraParams.allowLinkStealing=false"
```
