### DISCUSSION TITLE
Tool for migration of broker data from VM broker to Cloud broker

### DISCUSSION THREAD

**Discussion by Mohanavalli-A** [arkmq-org/arkmq-org-broker-operator#642] [General] [answered]
Hi Team,

Currently we are working on migration of the Artemis brokers from VM to cloud using the Artemis Cloud IO operator. We are looking for a way to migrate the broker data from the VM into the cloud broker. Do we have any tool that will aid with this activity ? Can we use `artemis data exp` on VM and `artemis data imp` in the cloud broker? Please advice.

Thanks,
Mohanavalli A

**Comment by brusdev** [comment, marked as answer]
Hi @Mohanavalli-A, I confirm that the only available tool to import  the broker data is the ActiveMQ Artemis CLI using the command ` artemis data imp`. To execute the command `artemis data imp` from outside the Kubernetes cluster an exposed acceptor is required, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: my-artemis
spec:
  acceptors:
  - name: my-acceptor
    port: 61617
    sslEnabled: true
    expose: true
```
