### DISCUSSION TITLE
Ingress missing with multiple nodes?

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#647] [Q&A]
I'm trying to create a two node Artemis MQTT broker with your latest operator version 1.0.13

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: exoo
spec:
  deploymentPlan:
    size: 2
    image: placeholder
    persistenceEnabled: true
    messageMigration: true
  acceptors:
    - name: mqtt-acceptor
      protocols: MQTT
      port: 61616
      expose: false
      sslEnabled: false
    - name: mqtt-tls-acceptor
      protocols: MQTT
      port: 61617
      expose: true
      sslEnabled: true
      needClientAuth: true
      verifyHost: false
```

but I cannot see any ingress entry related to the exposed acceptor. Is it the right behaviour?
