### DISCUSSION TITLE
Broker name

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#665] [Q&A]
Is it possible to change via CRD or brokerProperties the broker name that by default is **amq-broker** as I found within the broker.xml configuration file

```xml
<configuration xmlns="urn:activemq"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:xi="http://www.w3.org/2001/XInclude"
               xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">

   <core xmlns="urn:activemq:core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="urn:activemq:core ">

      <name>amq-broker</name>
```

**Comment by gaohoward** [comment]
Yes it is possible, simple add a name entry in the brokerProperties, such as 
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  brokerProperties:
  - name=new-amq-broker
```
