### DISCUSSION TITLE
Jolokia username and password

### DISCUSSION THREAD

**Discussion by lordigon** [arkmq-org/arkmq-org-broker-operator#668] [Q&A]
Is it possible to set Jolokia Username and password? 
Trying to invoke this url from inside the cluster

```
curl -v -u anyuser:anypassword http://amq-broker-hdls-svc:8161/console/jolokia/read/org.apache.activemq.artemis:broker=/%22amq-broker/%22/Status
```

I can use any username and password to be able to get a response.
Does a secret exist for this Jolokia authentication info?

**Comment by gaohoward** [comment]
Hi you need to enable security in the Broker cr.  for example:
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    requireLogin: true
  adminUser: admin
  adminPassword: admin
```
where `requireLogin: true` enables the broker to require Login and `adminUser` and `adminPassword` to configure an admin user to use. This way broker uses the built-in propertiesLoginModule to do all authentications.

Another way to configure a console's security is to use the [jaas configuration options](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#configuring-jaas-for-brokers) to directly configure your login modules for the jolokia access. Have a look at [this discussion](https://github.com/artemiscloud/activemq-artemis-operator/discussions/559)
