### DISCUSSION TITLE
How to setup connector if we enable ssl on broker side

### DISCUSSION THREAD

**Discussion by wangshu3000** [arkmq-org/arkmq-org-broker-operator#713] [Q&A] [answered]
Hi 

I have 2 brokers deployment. 
I enabled the hapolicy replication by using initcontainer. 
I'm trying to enable the ssl on my brokers. After enable the ssl for 61616 port. My cluster is broken, they can not connect with each other and they work as isolate brokers.

I see the generated broker.xml file, the acceptor is already configured as accept ssl connection like below. The url is generated by operator automatically.
`<acceptor name="all">tcp://artemis-ss-0.artemis-hdls-svc.namespace.svc.cluster.local:61616?protocols=AMQP,CORE,HORNETQ,MQTT,OPENWIRE,STOMP;sslEnabled=true;keyStorePath=/etc/keystore.ks;keyStorePassword=xxx;trustStorePath=/etc/truststore.ts;trustStorePassword=xxx;connectionsAllowed=25;amqpMinLargeMessageSize=204800;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor>`

The connector is still original url without ssl parameters. 
<connector name="artemis">tcp://artemis-ss-0.artemis-hdls-svc.namespace.svc.cluster.local:61616</connector>

I tried to use connector from the CR, but the host field is required and doesn't support variable like the ingressHost field.

Is there any we i can configure the connector to use ssl when connecting the cluster?

Thanks.

**Comment by brusdev** [comment, marked as answer]
@wangshu3000 you could use brokerProperties with the broker prefix to enable SSL for your connector, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: my-name
spec:
  brokerProperties:
    - "broker-0.connectorConfigurations.f1.params.HOST=my-name-ss-1.my-name-hdls-svc"
    - "broker-0.connectorConfigurations.f1.params.PORT=..."
    - "broker-0.connectorConfigurations.f1.params.sslEnabled=true"
    - "broker-0.connectorConfigurations.f1.params.trustStorePath=..."
    - "broker-0.connectorConfigurations.f1.params.trustStorePassword=..."
    - "broker-1.connectorConfigurations.f1.params.HOST=my-name-ss-0.my-name-hdls-svc"
    - "broker-1.connectorConfigurations.f1.params.PORT=..."
    - "broker-1.connectorConfigurations.f1.params.sslEnabled=true"
    - "broker-1.connectorConfigurations.f1.params.trustStorePath=..."
    - "broker-1.connectorConfigurations.f1.params.trustStorePassword=..."
```
