### DISCUSSION TITLE
JMS API for artemis on EKS cluster

### DISCUSSION THREAD

**Discussion by git-syeda** [arkmq-org/arkmq-org-broker-operator#728] [General]
Hi team,
We would like to know how to call artemis API url using JMS to perform admin operations. Also please help us with the complete set up on how to connect.

@brusdev please help us with the answer

**Comment by brusdev** [comment]
@git-syeda the simplest way to perform admin operations using JMS from inside the cluster is using an acceptor service, i.e.  the service name that points to the acceptor `my-acceptor` of the broker 0 is broker-my-acceptor-0-svc
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
spec:
  acceptors:
  - name: my-acceptor
    port: 61626
```

The simplest way to perform admin operations using JMS from outside the cluster is using an acceptor ingress, i.e.  the ingress name that points to the acceptor `my-acceptor` of the broker 0 is broker-my-acceptor-0-svc-ing
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
spec:
  acceptors:
  - name: my-acceptor
    port: 61626
    expose: true
    sslEnabled: true
```

For further details on setting up SSL connections with ArtemisCloud Operator, see https://artemiscloud.io/docs/tutorials/ssl_broker_setup/

For further details on using JMS to perform admin operations see the Apache ActiveMQ Artemis [management example](https://github.com/apache/activemq-artemis/tree/2.31.0/examples/features/standard/management) or send an email to users@activemq.apache.org
