### DISCUSSION TITLE
How to configure security settings, like 'populate-validated-user' and 'security-invalidation-interval'

### DISCUSSION THREAD

**Discussion by eanbiso** [arkmq-org/arkmq-org-broker-operator#750] [Q&A] [answered]
Hi support,
I would need to understand how to configure some security settings, like the 'populate-validated-user' and 'security-invalidation-interval' properties, using Artemis in the k8s context.
I was looking for the configuration in the [broker_activemqartemis_crd.yaml (v1.0.16)](https://github.com/artemiscloud/activemq-artemis-operator/blob/v1.0.16/deploy/crds/broker_activemqartemis_crd.yaml), but I didn't find these settings.
Can you help me?

A further question: which is the best place to figure out how to configure security settings described at [activemq.apache.org](https://activemq.apache.org/components/artemis/documentation/latest/security.html) into k8s context?

**Comment by brusdev** [comment, marked as answer]
@eanbiso you can use the broker properties to configure those settings, i.e.
https://activemq.apache.org/components/artemis/documentation/latest/configuration-index.html#broker-properties
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-redistribution
spec:
  brokerProperties:
    - "populateValidatedUser=true"
    - "securityInvalidationInterval=5000"
```
