### DISCUSSION TITLE
How to set defaultMqttSessionExpiryInterval on MQTT acceptors

### DISCUSSION THREAD

**Discussion by eanbiso** [arkmq-org/arkmq-org-broker-operator#829] [Q&A] [answered]
Hi support,
I would need to understand how I can configure the property 'defaultMqttSessionExpiryInterval' on an MQTT acceptor using Artemis in the k8s context.
Is this possible using the broker property "acceptorConfigurations.<ACCEPTOR_NAME>.extraParams.defaultMqttSessionExpiryInterval" in a way like this
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-mqtt
spec:
  acceptors:
    - name: mqtt-plain
      protocols: MQTT
      port: 1884
  brokerProperties:
    - "acceptorConfigurations.mqtt-plain.extraParams.allowLinkStealing=false"
    - "acceptorConfigurations.mqtt-plain.extraParams.defaultMqttSessionExpiryInterval=300"
```
?

Many thanks
