### DISCUSSION TITLE
Is possible to access to artemis console 8161?

### DISCUSSION THREAD

**Discussion by malejoavilas** [arkmq-org/arkmq-org-broker-operator#909] [General]
Hello,

I have my artemis cluster and works well, I have 2 brokers, but I try to create an ingress to access to the console via web 8161, the webpage loads but I can't login in it, when I set the user and password the page just loads again, but if I use the Endpoint Service IP I can login to the console. Is there a way to access with an ingress?

**Comment by brusdev** [comment]
@malejoavilas have you already tried the `ingress` expose mode?
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  console:
    expose: true
    exposeMode: ingress
    ingressHost: artemis-broker-console.my-domain.com
```
