### DISCUSSION TITLE
No broker after upgrading to operator 1.2.1

### DISCUSSION THREAD

**Discussion by lnthai2002** [arkmq-org/arkmq-org-broker-operator#918] [Q&A] [answered]
Hello,
We have recently upgraded to artemis operator 1.2.1 and we noticed that the broker pod does not spawn anymore. I dont see any error in the operator controller, the ActiveMqArtemis resource is created in the watch namespace but there is artemis statefulset created. When i describe the ActiveMqArtemis resource in the watched namespace, i noticed this:
![image](https://github.com/artemiscloud/activemq-artemis-operator/assets/1395357/b9b54050-9792-45df-b768-19235c752281)
I'm not sure why it complain about ingress. How can i get more info about the invalid ingress setting?

**Comment by lnthai2002** [comment]
here is my def for the ActiveMqArtemis
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: activemq-artemis-broker
spec:
  acceptors:
    - name: "all-protocols-acceptor"
      bindToAllInterfaces: true
      port: 61617
#      protocols: "CORE" # not defining protocols make broker enable all protocols (CORE,STOMP, AMQP,...) support
  addressSettings:
    applyRule: merge_all
    addressSetting:
    - match: '#'
      deadLetterAddress: DLQ
      expiryAddress: ExpiryQueue
      redistributionDelay: 60000
      redeliveryDelay: 0
      maxSizeBytes: "-1"
      messageCounterHistoryDayLimit: 10
      addressFullPolicy: PAGE
      autoCreateQueues: true
      autoCreateAddresses: true
      autoCreateJmsQueues: true
      autoCreateJmsTopics: true
      autoDeleteQueues: false
      autoDeleteCreatedQueues: false
      autoDeleteAddresses: false
      defaultConsumerWindowSize: 0
    - match: 'JOB_QUEUE.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
    - match: 'CRON_JOB_QUEUE.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
    - match: 'QUEUE.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
    - match: 'TOPIC.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: 0
      autoDeleteAddresses: true
    - match: 'TOPIC.internal.#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete to avoid delete due to temporary lost connection
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: -1
      autoDeleteAddresses: true
    - match: 'TOPIC.retro.#'
      retroactiveMessageCount: 1
      autoDeleteQueues: true
      autoDeleteQueuesDelay: 0
      autoDeleteQueuesMessageCount: -1
    - match: '$.artemis.internal.#'
      autoDeleteQueues: false
      autoDeleteAddresses: true
    - match: 'internal-ncp-deployment'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: -1
      autoDeleteAddresses: true
    - match: 'internal-cs-log-level-#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: -1
      autoDeleteAddresses: true
    - match: 'internal_core_service_interruption-#'
      autoDeleteQueues: true
      autoDeleteCreatedQueues: true
# wait 5 MIN before delete queues
      autoDeleteQueuesDelay: 300000
      autoDeleteQueuesMessageCount: -1
      autoDeleteAddresses: true
  console:
    expose: true
    sslEnabled: false
  deploymentPlan:
    size: {{ .Values.replicas }}
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 30
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 30
    requireLogin: true
    messageMigration: true
    persistenceEnabled: {{ .Values.persistence.enabled }}
    {{- if .Values.persistence.enabled }}
    podSecurityContext:
      fsGroup: 0
    storage:
      size: {{ .Values.persistence.size }}
      storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    resources:
      requests:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
  adminUser: {{ .Values.artemisUser }}
  adminPassword: {{ .Values.artemisPassword }}
```
