### DISCUSSION TITLE
How to modify the Broker args?

### DISCUSSION THREAD

**Discussion by win5923** [arkmq-org/arkmq-org-broker-operator#931] [Q&A]
Hello,
I'm using operator 1.21 and would like to ask how to modify the args of `artemis-broker-container-init`. I want to change `--http-host`, but if I use the following settings, there will be an error. Any advice would be greatly appreciated!
```
Removing provided -XX:+UseParallelOldGC in favour of artemis.profile provided option
Platform is x86_64
Running server env: home: /home/jboss AMQ_HOME /opt/amq CONFIG_BROKER  RUN_BROKER false
NO CONFIG_BROKER defined
Configuring Broker at /amq/init/config
config Using instanceDir: /home/jboss/amq-broker
Broker will be clustered
Setting journal type to nio
Creating Broker with args --silent --role admin --name amq-broker --http-host artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local --java-options=-Djava.net.preferIPv4Stack=true  --user XXXXX --password XXXXX  --allow-anonymous --no-amqp-acceptor --no-hornetq-acceptor --no-mqtt-acceptor --no-stomp-acceptor --require-login --http-host 0.0.0.0 --relax-jolokia --clustered --cluster-user XXXXX --cluster-password XXXXX --host artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local --nio at /home/jboss/amq-broker

option '--http-host' (<httpHost>) should be specified only once
Usage: artemis help [<args>...]
use 'help <command>' for more information
      [<args>...]
Checking yacfg file under dir: 
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
Generating jgroups-ping.xml, current dir is: /tmp/remote_source/app, AMQHOME: /opt/amq
APPLICATION_NAME is not set
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
Setting redistribution-delay to zero.
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
sed: can't read /home/jboss/amq-broker/etc/jolokia-access.xml: No such file or directory
Using acceptors from environment and removing existing entries
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
sed: can't read /home/jboss/amq-broker/etc/broker.xml: No such file or directory
Removing hardcoded -Xms -Xmx from artemis.profile in favour of JAVA_OPTS in log above
sed: can't read /home/jboss/amq-broker/etc/artemis.profile: No such file or directory
Configure logging
/opt/amq/bin/launch.sh: line 291: /home/jboss/amq-broker/etc/artemis.profile: No such file or directory
/opt/amq/bin/launch.sh: line 292: /home/jboss/amq-broker/etc/artemis.profile: No such file or directory
/opt/amq/bin/launch.sh: line 293: /home/jboss/amq-broker/etc/artemis.profile: No such file or directory

```

Here is my ActiveMQArtemis:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  acceptors:
    - name: activemq-mqtt
      expose: false
      port: 5672
      protocols: mqtt
      sslEnabled: true
      sslSecret: amq-ssl-secret

  
  deploymentPlan:
    size: 1
    initImage: quay.io/artemiscloud/activemq-artemis-broker-init:artemis.2.33.0
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.33.0
    journalType: nio
    enableMetricsPlugin: true
    containerSecurityContext:
      runAsNonRoot: true
  env:
    - name: AMQ_EXTRA_ARGS
      value: "--require-login --http-host 0.0.0.0 --relax-jolokia"
```

**Comment by brusdev** [comment]
@win5923 you could use the system property `webconfig.bindings.artemis.uri` to customize the http host but listening on 0.0.0.0 is not secure, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  env:
  - name: JAVA_ARGS_APPEND
    value: -Dwebconfig.bindings.artemis.uri=http://0.0.0.0:8161
```

**Reply by win5923** [reply]
hi @brusdev, 
Thanks for your reply, but I still encountered CORS issues following your steps. I found that someone has a similar problem.
https://stackoverflow.com/a/71207182/22183172

![image](https://github.com/artemiscloud/activemq-artemis-operator/assets/56353753/765468d6-897d-4524-8673-2bbfc5964aed)


Is there any way to modify the contents of `jolokia-access.xml` or change the `--http-host` args?

```
[jboss@artemis-broker-ss-0 ~]$ cat amq-broker/etc/jolokia-access.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

<!-- This policy file controls the Jolokia JMX-HTTP bridge security options for the web console.
   see: https://jolokia.org/reference/html/security.html -->
<restrict>

    <cors>
        <!-- Allow cross-origin access from the origins that match the following pattern ... -->
        <allow-origin>*://artemis-broker-ss-0.artemis-broker-hdls-svc.activemq-artemis-operator.svc.cluster.local*</allow-origin>


        <!-- Options from this point on are auto-generated by Create.java from the Artemis CLI -->
        <!-- option relax-jolokia used, so strict-checking will be removed here -->
    </cors>

</restrict>[jboss@artemis-broker-ss-0 ~]$
```

**Comment by win5923** [comment]
I solved the issue by adding a launch.sh config map and including it in the initContainer.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: artemis-jolokia-access
  namespace: activemq-artemis-operator
data:
  launch.sh: |
    #!/bin/sh
    export BROKER_IP="0.0.0.0"
    ....
```

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  resourceTemplates:
    - selector:
        kind: "StatefulSet"
      patch:
        kind: "StatefulSet"
        spec:
          template:
            spec:
              initContainers:
              - name: "artemis-broker-container-init"
                volumeMounts:
                - name: jolokia-access
                  mountPath: /opt/amq/bin/launch.sh
                  subPath: launch.sh
                  readOnly: true
              volumes:
              - name: jolokia-access
                configMap:
                  name: artemis-jolokia-access
                  items:
                    - key: launch.sh
                      path: launch.sh
                      mode: 0755
```
