### DISCUSSION TITLE
Federation in ArtemisCloud

### DISCUSSION THREAD

**Discussion by beaver71** [arkmq-org/arkmq-org-broker-operator#971] [General] [answered]
What is the simplest way to configure federation (see https://activemq.apache.org/components/artemis/documentation/latest/federation-address.html#address-federation) between an ArtemisCloud instance and another external Artemis?
This is a sample configuration for Artemis standard setup (non ArtemisCloud):

```
	<connectors>
	   <connector name="artemis-external">tcp://<external-address>:61616</connector>
	</connectors>
```

```
	<federations>
	   <federation name="artemis-fed" user="***" password="***">
		  <upstream name="artemis-external-up">
			  <static-connectors>
				 <connector-ref>artemis-external</connector-ref>
			  </static-connectors>
			  <policy ref="address-policy"/>
		  </upstream>
		  <address-policy name="address-policy">
			 <include address-match="test" />
		  </address-policy>
	   </federation>
	</federations>
```

**Comment by brusdev** [comment]
@beaver71 are the ArtemisCloud instance and another external Artemis in the same Kubernetes cluster? If not is the ArtemisCloud instance able to reach the  external Artemis?

**Reply by beaver71** [reply]
No, the artemis external is not in the same k8s cluster but it is reachable by the ArtemisCloud instance

**Comment by brusdev** [comment, marked as answer]
The simplest way to configure federation is by using broker properties, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  brokerProperties:
    - connectorConfigurations.artemis-external.factoryClassName=org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
    - connectorConfigurations.artemis-external.params.host=<external-address>
    - connectorConfigurations.artemis-external.params.port=61616
    - federationConfigurations.artemis-fed.credentials.user=***
    - federationConfigurations.artemis-fed.credentials.password=***
    - federationConfigurations.artemis-fed.addressPolicies.address-policy.includes.just-b.addressMatch=test
    - federationConfigurations.artemis-fed.upstreamConfigurations.artemis-external-up.connectionConfiguration.staticConnectors=artemis-external
    - federationConfigurations.artemis-fed.upstreamConfigurations.artemis-external-up.policyRefs=address-policy
```
