### DISCUSSION TITLE
How to create a multicast address with two queues

### DISCUSSION THREAD

**Discussion by cbasener** [arkmq-org/arkmq-org-broker-operator#992] [General] [answered]
Hello there,
I don't know how to create a multicast address with two queues, like described here [Artemis Documentation](https://activemq.apache.org/components/artemis/documentation/).
Also the provided [Example](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/examples/address/address_topic.yaml) does not provide any solution.
Can somebody please give me hint how this is done?

Best regards

**Comment by brusdev** [comment, marked as answer]
@cbasener you can use [broker properties](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#configuring-brokerproperties) to create a multicast address with two queues, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-addresses
spec:
  brokerProperties:
    - "addressConfigurations.TOPIC1.routingTypes=MULTICAST"
    - "addressConfigurations.TOPIC1.queueConfigs.QUEUE1.address=TOPIC1"
    - "addressConfigurations.TOPIC1.queueConfigs.QUEUE1.routingType=MULTICAST"
    - "addressConfigurations.TOPIC1.queueConfigs.QUEUE2.address=TOPIC1"
    - "addressConfigurations.TOPIC1.queueConfigs.QUEUE2.routingType=MULTICAST"
```
