### DISCUSSION TITLE
How to enable sslAutoReload for console?

### DISCUSSION THREAD

**Discussion by doxsch** [arkmq-org/arkmq-org-broker-operator#999] [Q&A] [answered]
I am currently securing the endpoints and acceptors with SSL certificates.

How can it be configured so that the certificates are updated without a restart?

**Comment by brusdev** [comment, marked as answer]
The auto reload of the acceptor certificates can be enabled by using the the broker properties and the auto reload of the console certificates can be enabled by using the webconfig system properties, i.e.

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-console
spec:
  acceptors:
    - name: my-acceptor
      port: 61626
      sslEnabled: true
      sslSecret: my-tls-secret
  console:
    expose: true
    sslEnabled: true
    sslSecret: my-tls-secret
  brokerProperties:
    - "acceptorConfigurations.my-acceptor.params.sslAutoReload=true"
  env:
    - name: JAVA_ARGS_APPEND
      value: -Dwebconfig.bindings.artemis.sslAutoReload=true
```
